FROM texlive/texlive:latest-full


 RUN apt-get -y update && \
        apt-get -y upgrade && \
        apt-get -y install --no-install-recommends wget && \
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
        apt-get -y install --no-install-recommends ./google-chrome-stable_current_amd64.deb  \
        make \
        npm \
        python3 \
        python3-pip \
        nodejs && \
        apt-get -y autoremove && \
        pip install --no-cache-dir --break-system-packages \
        Sphinx \
        Pillow  \
        sphinxcontrib-mermaid \
        sphinxcontrib-applehelp \
        sphinxcontrib-devhelp \
        sphinxcontrib-htmlhelp \
        sphinxcontrib-jsmath \
        sphinxcontrib-qthelp \
	sphinxcontrib-httpdomain \
        sphinx-book-theme \
        sphinx_rtd_theme \
        docxbuilder \
        sphinxemoji \
        myst-parser \
        sphinx-markdown-builder \
        rinohtype \
        Jinja2 \
	sphinx-toolbox \
        docutils && \
        npm install -g npm@latest && \
        npm install -g puppeteer --unsafe-perm=true && \
        npm install -g mermaid && \
        npm install -g @mermaid-js/mermaid-cli && \
        apt-get clean && \ 
        rm -rf /var/lib/apt/lists/*

